{{- if and (index .Values "argo-cd").applicationSet.enabled .Values.harness.networkPolicy.create (or (index .Values "argo-cd").applicationSet.metrics.enabled (index .Values "argo-cd").applicationSet.webhook.ingress.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "argo-cd.applicationSet.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" (index .Values "argo-cd").applicationSet.name "name" (index .Values "argo-cd").applicationSet.name) | nindent 4 }}
spec:
  ingress:
  {{- if (index .Values "argo-cd").applicationSet.webhook.ingress.enabled }}
    - ports:
        - port: webhook
  {{- end }}
  {{- if (index .Values "argo-cd").applicationSet.metrics.enabled }}
    - from:
        - namespaceSelector: {}
      ports:
        - port: metrics
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "argo-cd.selectorLabels" (dict "context" . "name" (index .Values "argo-cd").applicationSet.name) | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
