apiVersion: v2
name: gitops-helm
description: A Helm chart for Harness GitOps Agent - for more information, please visit https://developer.harness.io/docs/category/gitops.
version: 1.1.5
dependencies:
  - name: argo-cd
    version: 5.53.1
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
