{{- if .Values.upgrader.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.agent.name }}-agent-upgrader
  namespace: {{ .Release.Namespace | quote }}
spec:
  schedule: {{ .Values.upgrader.cron }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.upgrader.startDeadline }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.upgrader.name }}
          containers:
              - name: upgrader
                image: {{ .Values.upgrader.image }}
                imagePullPolicy: Always
                env:
                  - name: POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
            {{- if .Values.agent.proxy.enabled }}
                - name: HTTPS_PROXY
                  value: {{ .Values.agent.proxy.httpsProxy }}
                - name: HTTP_PROXY
                  value: {{ .Values.agent.proxy.httpProxy }}
                - name: NO_PROXY
                  value: localhost,argocd-repo-server,argocd-redis,127.0.0.1,argocd-redis-ha-haproxy,kubernetes.default.svc,{{ .Values.agent.name }}-agent
            {{- end }}
                volumeMounts:
                  - name: config-volume
                    mountPath: /etc/config
                  - name: certvol
                    mountPath: /tmp/ca.bundle
                    subPath: ca.bundle
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Values.agent.name }}-agent-upgrader
            - name: certvol
              secret:
                secretName: {{ .Values.agent.name }}-agent-ca
                optional: true
                items:
                  - key: ca.bundle
                    path: ca.bundle
          restartPolicy: Never
---
{{- end }}