{{- if .Values.upgrader.enabled }}
apiVersion: v1
data:
  config.yaml: |
    mode: GitopsAgent
    dryRun: false
    workloadName: {{ .Values.agent.name }}
    namespace: {{ .Release.Namespace }}
    containerName: gitops-agent
    {{- if .Values.harness.configMap.http.mtls }}
    clientCertificateFilePath: {{ .Values.upgrader.config.clientCertificateFilePath }}
    clientCertificateKeyFilePath: {{ .Values.upgrader.config.clientCertificateKeyFilePath }}
    {{- end }}
    gitopsAgentConfig:
      upgrader:
        all: {{ .Values.upgrader.config.upgradeAll }}
      gitopsServerHost: {{ .Values.harness.gitopsServerHost }}
      {{- if .Values.harness.secrets.caData.enabled }}
      caData: /tmp/ca.bundle
      {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Values.agent.name }}-upgrader
  namespace: {{ .Release.Namespace | quote }}
---
{{- end }}