{{- if .Values.harness.flux.enabled }}
apiVersion: v1
metadata:
  name: argocd-redis
  labels:
    {{- include "harness.agentLabels" (dict "context" . "component" .Values.agent.name "name" "argocd-redis") | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  auth: {{ .Values.harness.secrets.redisPassword }}
kind: Secret
type: Opaque
{{- end }}