apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "harness.agentLabels" (dict "context" . "component" .Values.agent.name "name" "agent-secret") | nindent 4 }}
  name: argocd-harness-plugin
  namespace: {{ .Release.Namespace }}
data:
  harness.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-harness-plugin
    spec:
      allowConcurrency: {{ .Values.harness.argocdHarnessPlugin.allowConcurrency }}
      discover:
        find:
          command:
            {{- toYaml .Values.harness.argocdHarnessPlugin.discover.find.command | nindent 12 }}
      init:
        command:
          {{- toYaml .Values.harness.argocdHarnessPlugin.init.command | nindent 10 }}
      generate:
        command:
          {{- toYaml .Values.harness.argocdHarnessPlugin.generate.command | nindent 10 }}
      lockRepo: {{ .Values.harness.argocdHarnessPlugin.lockRepo }}
