{{- if .Values.agent.createClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.agent.harnessName }}-agent
  labels:
    {{- include "harness.agentLabels" (dict "context" . "component" .Values.agent.name "name" .Values.agent.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.agent.harnessName }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "harness.agentServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
