{{- $argo := (index .Values "argo-cd") -}}
{{- if .Values.harness.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "harness.labels" (dict "context" . "component" $argo.server.name "name" .Values.agent.name) | nindent 4 }}
  name: .Values.agent.name
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      {{- include "harness.selectorLabels" (dict "context" . "name" .Values.agent.name) | nindent 6 }}
  policyTypes:
  - Ingress
{{- end }}
