{{- if .Values.harness.createClusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argo-cd.repoServer.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "harness.labels" (dict "context" . "component" .Values.repoServer.name "name" .Values.repoServer.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argo-cd.repoServer.fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "argo-cd.repoServerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
