{{- if .Values.harness.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" ".Values.argo-cd.repoServer.name" "name" ".Values.argo-cd.repoServer.name") | nindent 4 }}
  name: {{ template "argo-cd.repoServer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
          {{- include "argo-cd.selectorLabels" (dict "context" . "name" .Values.agent.name) | nindent 10 }}
        - podSelector:
            matchLabels:
          {{- include "argo-cd.selectorLabels" (dict "context" . "name" ".Values.argo-cd.controller.name") | nindent 10 }}
    {{- if .Values.notifications.enabled }}
        - podSelector:
            matchLabels:
          {{- include "argo-cd.selectorLabels" (dict "context" . "name" ".Values.argo-cd.notifications.name") | nindent 10 }}
    {{- end }}
    {{- if .Values.applicationSet.enabled }}
        - podSelector:
            matchLabels:
          {{- include "argo-cd.selectorLabels" (dict "context" . "name" ".Values.argo-cd.applicationSet.name") | nindent 10 }}
    {{- end }}
      ports:
        - port: repo-server
          protocol: TCP
  {{- if ".Values.argo-cd.repoServer.metrics.enabled" }}
    - from:
        - namespaceSelector: {}
      ports:
        - port: metrics
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "argo-cd.selectorLabels" (dict "context" . "name" ".Values.argo-cd.repoServer.name") | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
