{{- $argo := (index .Values "argo-cd") -}}
{{- if $argo.configs.params.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "harness.labels" (dict "context" . "component" $argo.server.name "name" "cmd-params-cm") | nindent 4 }}
  {{- if $argo.configs.params.annotations }}
  annotations:
  {{- range $key, $value := $argo.configs.params.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  {{- include "argo-cd.config.params" . | trim | nindent 2 }}
{{- end }}
